### ISSUE TITLE
Set AppVeyor (CI) for .NET builds

### ISSUE THREAD

**Issue by dblock** [dblock/waffle#165]
https://appveyor.com will work for the .NET part of the build.

**Comment by hazendaz** [comment]
@dblock I'm working this one.  All new for me and not knowing enough about .net it's taking a bit.  However, I guess it's been nearly a year since this request so with any luck, I'll get it working by the 12th :)

**Comment by hazendaz** [comment]
Getting closer....local build not refers to nunit pulled from nuget.  Using 2.6.4.  Up on appveyor, it fails further down trying to get version 2.6.3 so more to research.  Progress anyways...

C:\projects\waffle\Waffle.proj(65,5): error MSB6004: The specified task executable location "C:\Program Files (x86)\NUnit 2.6.3\bin\nunit-console-x86.exe" is invalid.
Command exited with code 1

**Comment by hazendaz** [comment]
.net side is now working.  fails when attempting to run java tests in waffle-jna with native issue.  Getting much closer...

**Comment by hazendaz** [comment]
I didn't find an example using jna that had maven tests turned on.  All examples I found had it turned off so I'm guessing there is a reason that it doesn't work.  So I did the same if built on appveyor only.  So at the present, we have at least .net code built with tests and java code built without tests.

**Comment by hazendaz** [comment]
Closing this issue and will reopen new issue related to getting unit tests running.
