### ISSUE TITLE
No support for authorization in service provider

### ISSUE THREAD

**Issue by csms** [dblock/waffle#188]
This issue is created as something to refer to for pull request: #174

Once the authenticaiton provider(e.g the Active Directory) has authenticated the principal, waffle 
currently assumes that the principal is authorized to use the service that the service provider(e.g service/application) that is using waffle to authenticate towards AD. This may not be the case. The principal may very well be in the Active Directory but not be authorized to use the service that the current service provider provides.

**Comment by hazendaz** [comment]
Thanks for the contribution!

**Comment by csms** [comment]
Hey - wait what happened? Did you already merge it in? I was working on a demo and documentation per your request :-)
