### ISSUE TITLE
Waffle resets roles with ie11 (not in chrome)

### ISSUE THREAD

**Issue by davidjonsson** [dblock/waffle#201]
Im a bit confused here. Ive added a PostAuthFilter right after waffle authentication filter. I do some logic the first time a user logs in and add an authority if this logic is correct for the authenticated user. With chrome this works fine, the role gets added, etc. However, when running IE11 after some time (I log all roles each filter-chain) this role suddenly gets removed when a client is running ie11. Its like it resets to the default authority + group authorities.

    authentication.getAuthorities().add(new CLLManagerGrantedAuthority()); // This gets removed after some time

I have not changed the negotiateseurityfilter in my auth context configuration
    
    <bean id="waffleNegotiateSecurityFilter" class="waffle.spring.NegotiateSecurityFilter">
        <property name="Provider" ref="waffleSecurityFilterProviderCollection" />
    </bean>

And the filters are setup as follows

    <sec:custom-filter ref="waffleNegotiateSecurityFilter" position="BASIC_AUTH_FILTER" />
    <sec:custom-filter ref="postAuthFilter" after="BASIC_AUTH_FILTER" />

**Comment by dblock** [comment]
It would be useful to know if there's a re-negotiation happening right before this happens. Look at the HTTP traffic.

You should bring this up on the [discussions list](http://groups.google.com/group/waffle-users).

**Comment by davidjonsson** [comment]
Oh Im sorry, I move it to the discussion-list. Im sure it has something to do with IE having negotiation while chrome does the basic-fallback. Feel free to close this one

**Comment by dblock** [comment]
Closing.
