### ISSUE TITLE
Will waffle pull User details from Linux Domain Controller?

### ISSUE THREAD

**Issue by skumary2k** [dblock/waffle#202]
I have a Domain Controller running on Linux and a windows system connected to this DC. If I will run your code in the Windows machine will it give me all the groups from the Linux DC?

**Comment by dblock** [comment]
Please post this to the [mailing list](http://groups.google.com/group/waffle-users), thanks.

**Comment by dblock** [comment]
The answer btw is likely "yes". You should try it.

**Comment by skumary2k** [comment]
Thanks...I will try out...
