### ISSUE TITLE
waffle-jna shouldn't depend on slf4j-simple

### ISSUE THREAD

**Issue by mberndt123** [dblock/waffle#208]
Hi,

The title says it all really. Libraries should only depend on slf4j-api; the choice of the logging implementation should be left to the application. An application that uses waffle-jna may unintentionally end up with two slf4j implementations on the classpath, which can lead to the wrong one being chosen and logs being lost.

**Comment by hazendaz** [comment]
It is used for testing.  If you look carefully you will see it is tagged that way in the parent and listed otherwise as optional.  Is this causing you a problem?

--- Original Message ---

**Comment by mberndt123** [comment]
Hi,

yes, I do have the problem I described above, logs were not being written due to slf4j-simple being pulled in by (transitive) dependencies. However I suspect by now that this is actually due to an error on my part. I haven't quite figured it out but for some reason my sbt build definition seems to pull in optional dependencies. So sorry for the noise, this ticket can be closed. Have a nice day.

**Comment by hazendaz** [comment]
Thanks.  If your issue seems like it might be useful to others you could write up the situation and how it was resolved on the waffle user group.  At least I'm very curious how that was pulled in.

--- Original Message ---
