### ISSUE TITLE
Revert Change for using project.version

### ISSUE THREAD

**Issue by hazendaz** [dblock/waffle#220]
Slight Rant...After 2 hours of basically failure after failure on releasing 1.7.4, it is apparent that the change I made to try to make use of maven project.version rather than snapshot all over was a really bad thing.  What bugs me most is that after xx number of failures, it became obvious that I kept ending up with a partial release and all I needed to do was perform 'mvn deploy' to get it to sonatype.  All that said, I need to revert the change on the master and wanted to just note that if mvn;prepare completes even with failure, the project essentially can be deployed then just needs manual cleanup afterwards.  Lots learned, hours wasted.  Next time this needs to be seamless...

**Comment by hazendaz** [comment]
Not 100% convinced this was the issue as rolling this out of 1.7.4 proved not to the issue preventing release plugin from working.  No clue why it wasn't working properly.  I'm going to play around with this a bit more over the next week or so now that 1.7.4 is pushed out.  I'll leave this issue until this is solved.

**Comment by hazendaz** [comment]
This is not the issue with the release.  It's most likely the new release plugin as it failed on invoker.  Since we won't be releasing for a while now, I'm closing this issue.

**Comment by dblock** [comment]
Somewhere @hazendaz should write a post with a pie chart of how much effort goes into maintaining maven vs. maintaining business logic in this project ;)

**Comment by hazendaz** [comment]
Right!  Business logic thus far has been very small compaired to maintaining maven.  Seems every step forward maven makes recently a few steps back for users.  Maven is pretty complex when it comes down to it.  While we all like to think we use maven 3, that is just the core.  The plugins are all still based on maven 2.2.1 or lower and mostly java 5 or lower.  Only a couple are based on newer revisions of both maven and java.  While they are trying to fix the ills that have haughted maven for years and did mostly an incredible job so far, there have been some hiccups.  Another project I work on is also experiencing issues releasing code.  I don't have access there to see the specific issue but I'm convinced it's probably the release plugin.  Specifically on waffle, it has all kinds of invoker errors during release:prepare that ends up just getting the snapshot switched to release version then errors out.  At first I thought this change I made was causing it but reverting that from the code, setting it backup as snapshot across the board ended with same error.  The latest version I have this on is one maven "fixed" invoker to work with maven 3.3.1.  It sort of seems they broke backwards compatibility.  While I don't have a firm grasp on what the issue is completely yet, we have alternatives so we can still release as we need.  I assume though these issues will be resolved soon thus making things easy again.  I do have a 'base-parent' project on my @hazendaz which more or less waffle is on par with.  So definitely a place where i need to write as I figure out the issues.  I only recently officially released 'base-parent' with hopes that I can wire into other projects and stop with all the maven updates.  For now, that will have to become stable :)
