### ISSUE TITLE
1.7.4 release issues

### ISSUE THREAD

**Issue by hazendaz** [dblock/waffle#221]
Having some trouble getting 1.7.4 released as a result of prior noted issues.  I can deploy out to sonatype but it doesn't have a signatures so they won't allow it to pass scans and such so it won't load.  Will try again tomorrow.

As a side note, 1.7.4 is nearly everything from master.  So a few fixes and lots of updates.  I believe it will be last 1.7.x as soon as I can get it released.  Now if I still have issues, I can just go with 1.8.0 and be done with it.  1.8.0 will drop tomcat 5 and spring 2.  However, that means we wouldn't have a fix for bugs with tomcat integration.  So a toss up if we care or not.  I'll keep trying 1.7.4 for now...unless I get some feedback telling me otherwise :)

**Comment by bhamail** [comment]
Hi Jeremy,

In case it helps, this article looks useful: http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/#.VVSm6mD4m0E <http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/#.VVSm6mD4m0E>

At the end of the article, I especially like the idea of only triggering the “gpg” work during a release via a profile activation triggered by the act of releasing:

<profiles>
    <profile>
      <id>release-sign-artifacts</id>
      <activation>
        <property>
          <name>performRelease</name>
          <value>true</value>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

Dan

**Comment by hazendaz** [comment]
Thanks for the pointers.  I'm going to follow this tonight...

--- Original Message ---

**Comment by hazendaz** [comment]
Issue solved...1.7.4 is in the cycle to be released in next two hours.  The solution was much easier.  Didn't need to do anything to waffle.  I did still use the deploy rather than release plugin as something is broken there and this works just as well.  Sonatype parent already had GPG in it, so just needed to run the deploy with this profile -Psonatype-oss-release
