### ISSUE TITLE
How to authenticate a NTLM token that generate from separate computer

### ISSUE THREAD

**Issue by rswijesena** [dblock/waffle#225]
Hi Folks,

I am investigating  an issue. I have a situation like below.

I have two computers , say A and B configured with an active directory.Once i created a NTLM token from computer A, I need  pass that NTLM token  to the  computer B hosted application via HTTP GET method as a query parameter.

Once NTLM token received by computer B it will try to negotiate that token. But its giving me a error saying Caused by: com.sun.jna.platform.win32.Win32Exception: The token supplied to the function is invalid .

But if i tried above scenarios in one computer my application is working as expected.

is this a known issue?

Thanks
Roshan

**Comment by dblock** [comment]
This could be one of a thousand things. Usually we advise people to start with [Troubleshooting](https://github.com/dblock/waffle/blob/master/Docs/Troubleshooting.md).

You should bring any more questions up on the [mailing list](https://groups.google.com/forum/#!forum/waffle-users).
