### ISSUE TITLE
release 1.7.5 not in Maven central

### ISSUE THREAD

**Issue by oeil** [dblock/waffle#228]
Hi guys,

Could publish the 1.7.5 release to Maven central please? At the moment the latest release available there is 1.7.4.

Thanks you

**Comment by hazendaz** [comment]
1.7.4 currently is the latest version.  May I ask where are you finding references to 1.7.5?

--- Original Message ---

**Comment by oeil** [comment]
Oh ok - I saw the tag 1.7.5 (https://github.com/dblock/waffle/releases/tag/waffle-parent-1.7.5) so I thought it was a release.

Anyway thanks

**Comment by hazendaz** [comment]
There were some issues with maven release plugin at that time.  If I recall correctly I started pushing version up in a failed attempt to get around the issue.  Ultimately I found a work around so 1.7.4 could be released.

--- Original Message ---

**Comment by hazendaz** [comment]
Release tag for 1.7.5 has been deleted.  Full packaged 1.7.4 now in releases.
