### ISSUE TITLE
UnsatisfiedLinkError - Native Library - jnidispatch.dll

### ISSUE THREAD

**Issue by henriquels25** [dblock/waffle#257]
I have a problem using waffle and tomcat 7 to enable login via windows authentication.

Everything is working fine but everytime I deploy the application, I get this error:

    java.lang.UnsatisfiedLinkError: Native Library C:\Program Files    (x86)\Apache Software Foundation\Tomcat 7.0\work\Catalina\localhost\seedInventory\loader\com\sun\jna\win32-x86\jnidispatch.dll already loaded in another classloader

When I restart tomcat, it started working again. However, I want to be
able to deploy the application without restarting.

I see that this file jnidispatch.dll is still being used even after the undeploy and I can't delete it manually.

What could I do?

**Comment by dblock** [comment]
This is about where you put the `jna.jar`, check out http://wiki.apache.org/tomcat/HowTo#I.27m_encountering_classloader_problems_when_using_JNI_under_Tomcat. I suspect you need to move that to the shared Tomcat directory out of the app.

**Comment by henriquels25** [comment]
yeah, I have seen this link before I've done that. Unfortunatelly, it keeps showing me that error and creating the dll file in the work directory.

I have created the shared/lib directory, changed the catalina.properties to reference this directory, put the shared/lib directory in the PATH of windows and copied the jnidispatch.dll to this folder.

But it still giving me this error everytime deploy the application.

**Comment by dblock** [comment]
You shouldn't ever need to copy or have the `jnidispatch.dll` file anywhere! Remove it. JNA extracts this at runtime.

**Comment by henriquels25** [comment]
Thanks, I removed the dll and removed the jna.jar from my project and now it is working. 
I put the jna.jar in the tomcat lib folder.
