### ISSUE TITLE
Could not initialize class MITI.server.servlets.MirAxisServlet

### ISSUE THREAD

**Issue by r4un** [dblock/waffle#282]
Hi Guys,

I'm pretty new to waffle, so I'm hoping that i can get some help with a problem of mine - I'm trying to load implement waffle into a tomcat 7 server installation - but once i copy over the files, i get this error

(https://cloud.githubusercontent.com/assets/15611066/10881746/d869a054-8165-11e5-8899-8abe7b2f84c7.png)

Whats the problem? - thanks for the help in advance

**Comment by dblock** [comment]
There's no waffle on the stack here, so it's something unrelated.

**Comment by dblock** [comment]
Please use https://groups.google.com/forum/#!forum/waffle-users for questions.
