### ISSUE TITLE
Negotiate falls to NTLM instead of Kerberos

### ISSUE THREAD

**Issue by obat-edgeminds** [dblock/waffle#300]
Hi,

First of all, congratulations for your amazing work ! Waffle is going to replace our old and dirty pseudo-authentication mechanism.

I'm testing Waffle 1.8 on a brand new Tomcat 7.0.65 + JRE 1.8.0u66 setup (x64). The waffle-filter-1.8.0 and waffle-mixed-1.8.0 samples are working fine (SSO is OK, form authent too).

However, after analyzing the communication with WireShark, it seems that the negotiation ends with an NTLM authentication. From the docs, Waffle is supposed to support Kerberos protocol as part of the Negotiate provider, how can I enable it ? (Kerberos is a requirement for our security team)

Config : client Internet Explorer 8 is ran on a domain-joined Win7, Windows session is opened with a domain user on a Windows 2008 R2-level Active Directory domain). Web server is a Windows 2012 R2, domain-joined of course.

     Kind regards, Olivier.

**Comment by dblock** [comment]
This is most likely because you don't have a properly configured SPN. lCheck the FAQ/troubleshooting, etc.

Please use the [Google Group](http://groups.google.com/group/waffle-users) for questions.
