### ISSUE TITLE
Negotiate works from local machine, but not remote

### ISSUE THREAD

**Issue by kieranshaw** [dblock/waffle#332]
Hi,

Thanks for the really useful looking library, looks really promising. However, I'm having a bit of a problem.

I'm trying the waffle-filter demo and can get it to work beautifully on my local machine from a local browser (both Chrome and IE). However, if I go to another machine on our domain it fails and prompts for a username/password. I believe all of my IE settings are correct and I've only got Negotiate turned on, not NTLM.

For the local machine I get this log output:

`323063 [http-bio-9080-exec-5] DEBUG w.servlet.NegotiateSecurityFilter - GET /waffle-filter/index.jsp, contentlength: -1
323063 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - authorization: <none>, ntlm post: false
323063 [http-bio-9080-exec-5] DEBUG w.servlet.NegotiateSecurityFilter - previously authenticated Windows user: PHOEBUS\KS
323072 [http-bio-9080-exec-5] DEBUG w.servlet.NegotiateSecurityFilter - GET /waffle-filter/index.jsp, contentlength: -1
323072 [http-bio-9080-exec-5] DEBUG w.servlet.NegotiateSecurityFilter - authorization required
323082 [http-bio-9080-exec-5] DEBUG w.servlet.NegotiateSecurityFilter - GET /waffle-filter/index.jsp, contentlength: -1
324391 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - security package: Negotiate, connection id: fe80:0:0:0:90ab:cf9c:5796:5b31%28:53399
324392 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - header: Negotiate YHYGBisGAQUFAqBsMGqgMDAuBgorBgEEAYI3AgIKBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHqI2BDROVExNU1NQAAEAAACXsgjiBwAHAC0AAAAFAAUAKAAAAAYBsR0AAAAPS1MtUENQSE9FQlVT
324392 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - token buffer: 120 byte(s)
324881 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - continue token: oYH4MIH1oAMKAQGhDAYKKwYBBAGCNwICCqKB3wSB3E5UTE1TU1AAAgAAAA4ADgA4AAAAFcKJ4tE0kqHTNcuvwKAgAgAAAACWAJYARgAAAAYBsR0AAAAPUABIAE8ARQBCAFUAUwACAA4AUABIAE8ARQBCAFUAUwABAAoASwBTAC0AUABDAAQAGgBQAGgAbwBlAGIAdQBzAC4AbABvAGMAYQBsAAMAJgBLAFMALQBQAEMALgBQAGgAbwBlAGIAdQBzAC4AbABvAGMAYQBsAAUAGgBQAGgAbwBlAGIAdQBzAC4AbABvAGMAYQBsAAcACABRb6/ip3/RAQAAAAA=
324881 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - continue required: true
325318 [http-bio-9080-exec-5] DEBUG w.servlet.NegotiateSecurityFilter - GET /waffle-filter/index.jsp, contentlength: -1
325718 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - security package: Negotiate, connection id: fe80:0:0:0:90ab:cf9c:5796:5b31%28:53399
325718 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - header: Negotiate oXcwdaADCgEBoloEWE5UTE1TU1AAAwAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAABXCiOIGAbEdAAAAD7hMIfCqsQgtXqwxCh2wVj2jEgQQAQAAANvfUga0aMa0AAAAAA==
325718 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - token buffer: 121 byte(s)
326604 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - continue token: oRswGaADCgEAoxIEEAEAAAAcLWGAFq6mxQAAAAA=
326604 [http-bio-9080-exec-5] DEBUG w.s.s.NegotiateSecurityFilterProvider - continue required: false
327078 [http-bio-9080-exec-5] DEBUG w.servlet.NegotiateSecurityFilter - logged in user: PHOEBUS\KS (S-1-5-21-1808487615-3533925333-1214166427-3900)
327123 [http-bio-9080-exec-5] DEBUG w.servlet.NegotiateSecurityFilter - roles: PHOEBUS\KS, PHOEBUS\Domain Users, S-1-5-21-1808487615-3533925333-1214166427-513, Everyone, S-1-1-0, KS-PC\HelpLibraryUpdaters, S-1-5-21-3009095102-1392025643-2334872491-1014, KS-PC\ORA_DBA, S-1-5-21-3009095102-1392025643-2334872491-1013, BUILTIN\Administrators, S-1-5-32-544, BUILTIN\Network Configuration Operators, S-1-5-32-556, BUILTIN\Remote Desktop Users, S-1-5-32-555, BUILTIN\Users, S-1-5-32-545, NT AUTHORITY\INTERACTIVE, S-1-5-4, CONSOLE LOGON, S-1-2-1, NT AUTHORITY\Authenticated Users, S-1-5-11, NT AUTHORITY\This Organization, S-1-5-15, S-1-5-5-0-335838, S-1-5-5-0-335838, LOCAL, S-1-2-0, PHOEBUS\#Developers, S-1-5-21-1808487615-3533925333-1214166427-1261, PHOEBUS\PHL3_SQL_Server, S-1-5-21-1808487615-3533925333-1214166427-3272, PHOEBUS\Everyone @ Phoebus, S-1-5-21-1808487615-3533925333-1214166427-1135, PHOEBUS\#JavaTeam, S-1-5-21-1808487615-3533925333-1214166427-3740, PHOEBUS\NSQL_ReadWrite, S-1-5-21-1808487615-3533925333-1214166427-3929, PHOEBUS\#PHL3 TESTING CR, S-1-5-21-1808487615-3533925333-1214166427-2235, PHOEBUS\JenkinsAdmin, S-1-5-21-1808487615-3533925333-1214166427-3934, PHOEBUS\User Write Access, S-1-5-21-1808487615-3533925333-1214166427-3155, PHOEBUS\LSQL_ReadWrite, S-1-5-21-1808487615-3533925333-1214166427-4156, PHOEBUS\PHL5_OracleUtil, S-1-5-21-1808487615-3533925333-1214166427-3953, PHOEBUS\Developers, S-1-5-21-1808487615-3533925333-1214166427-3402, PHOEBUS\PHL11_ClientDB_ReadWrite, S-1-5-21-1808487615-3533925333-1214166427-3943, PHOEBUS\vSQLClientDB_ReadWrite, S-1-5-21-1808487615-3533925333-1214166427-3499, PHOEBUS\SAPs, S-1-5-21-1808487615-3533925333-1214166427-3974, PHOEBUS\JenkinsEdit, S-1-5-21-1808487615-3533925333-1214166427-4065, PHOEBUS\JenkinsRead, S-1-5-21-1808487615-3533925333-1214166427-3955, PHOEBUS\Environment_Access, S-1-5-21-1808487615-3533925333-1214166427-3702, PHOEBUS\Windows SBS Fax Users, S-1-5-21-1808487615-3533925333-1214166427-3129, PHOEBUS\Windows SBS Link Users, S-1-5-21-1808487615-3533925333-1214166427-3138, PHOEBUS\Windows SBS SharePoint_VisitorsGroup, S-1-5-21-1808487615-3533925333-1214166427-3135, PHOEBUS\Environment_Write_Access, S-1-5-21-1808487615-3533925333-1214166427-3788, PHOEBUS\Windows SBS Remote Web Workplace Users, S-1-5-21-1808487615-3533925333-1214166427-3128, Mandatory Label\High Mandatory Level, S-1-16-12288
327123 [http-bio-9080-exec-5] INFO  w.servlet.NegotiateSecurityFilter - successfully logged in user: PHOEBUS\KS`

Trying the same thing from remote gives me:

`336916 [http-bio-9080-exec-2] DEBUG w.servlet.NegotiateSecurityFilter - GET /waffle-filter/, contentlength: -1
336916 [http-bio-9080-exec-2] DEBUG w.servlet.NegotiateSecurityFilter - authorization required
336920 [http-bio-9080-exec-2] DEBUG w.servlet.NegotiateSecurityFilter - GET /waffle-filter/, contentlength: -1
338261 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - security package: Negotiate, connection id: 192.168.17.2:52766
338261 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - header: Negotiate YIIG4wYGKwYBBQUCoIIG1zCCBtOgMDAuBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCBp0EggaZYIIGlQYJKoZIhvcSAQICAQBuggaEMIIGgKADAgEFoQMCAQ6iBwMFACAAAACjggUWYYIFEjCCBQ6gAwIBBaEPGw1QSE9FQlVTLkxPQ0FMoiYwJKADAgECoR0wGxsESFRUUBsTa3MtcGMuUGhvZWJ1cy5sb2NhbKOCBMwwggTIoAMCARKhAwIBGqKCBLoEggS2uLAxnAn2SHT4xx1kpKpEsML553EKX2BwUXT8WFBjMREWQ7IyQxGVA/6WhAozYDVH/bgFshdeTzBSbfuDDHGpPw69fklEzuqFCFAOa9eXCdjYj8LvaAYRGsBikqMDofd4i5GrOZC/Gxrn6gAETTQ3wOYCnj+G9bBrsy2fFaBq2pYr4Zv1VtuzgIzxDKXbF1gmgZxcFD2acJHYl7RF0q6vnj19F/aWqFiirw/T3H283eIV9xYBrpoDkwEYmZoPVm3iww1ufgZ40itnuXWuJvvSAqS1PzHprzYzzJVy81qhrYfglyZDp7jeyijqaRuidpkGlzE4iXdU+PhNHs0CBiNEa0B2BGAOX94yXWdulwuWLRZDhsYOJk8CWzmp1S4dOdXMB1Cxx5RxyvTo93uZFBwRpWFh/jJKySjGOD37odXHh9PPOHO2f7Q2fS9riuLtyRvIo3p2A3zV+98gXEgiQbecWxOvmHCYL4fZZsKIRzA4g/I2bwuk00Y2oRe4OjIEOhzbh5q8fNh5jDme0w/ghwM5G0YKVPNRhrDnQ0rAkzu0V6yzqWmGARvEaSepxZzuS8HusPLSbzCZmonZaLPAVDHnTdvQvEKm4r8HuQXtY6Yg6L+LvoqIs8hT0LejCwxsGUrzjMgSIFhBkvLuJdZT4ThQx/vFriY0/LnQ4i94XhqYaNg+3UG/jphVWaX8O7+mhrn1G1ymIMSS1P21vyiqaHiyuus6oh0jzpy2eI0NKwJC2k+FxcMXnYs6Q/rpui0bpMOsA2eKKcRHPeSmPIQvOWvopkGEHquObOvvD2Q5M1x1IPj4oqJUaNWWIQkq6GiiBo/0pUtfmkMU7OTltJoNcs0XpMTAl7zTuQPwaKqsy9QWjXTeCqu9IzLwxUzcNot4oXA4IBfpmvlNe3pnDZM4V8M8SOkjllOcJabyb78gKAr2uNoGRJhFffRwnZVw0U9M1WA0DaqrEeSR7dXWTQIKlPCeR/rlEXSN3kSpS5PCWBGnWcqTOdAlfEfehP8MJtzeFGSmeI/M8PP5qorrKQfHJyo5uIWkbsGBRlBlAVUGbWCKitH7mCY5S+zeaIVQJ2PX+7owUYpZgWFvZG/KDeO6Yn8D2a2GicKOuTVJcjhRr9Eg6GyJNMeawPgdBY9ClE+Og9+6wFWBIJFaXbMgThDdETBnsPaUYwpmaOjpxv1mTwtS4ofmMFXGBLgBCRItdG2UXTsYeQnpRt501cB5e6JS/erApoc9PzOoPztUZI9V06AC5t6smYj/to1W4RuAf/k6s7opmK1oYwvxgO6qIBYO+z2WtwBfi5fXtpU4RpCcRSZrjyxrtuYoDJtTYyCvRTOwWni0uJhYJKEiqQCjCcCI4aVHI/n1dMZEby+xn4UE8oOcgR0lTOcEgj+CaoAyPje3xiNzPTaQmcD+Bpgau6fj8r6PH4eqUoy2KlRdBwTW1268miCQ4UI62iYJ1OytxrVAV2JoFLsnglPAgigAI5crj8z4rDkCgmZf5fPcqGCbDZF9U7t0qNX/z9hnk3fjY1FUSAVkOauuCMShTeEsxMWNVx0oBjKPmZhSIK/HquaW0hUTWQ+9P446Ypq17VwS7OAiWLDHCJjNTLV2pIIBTzCCAUugAwIBEqKCAUIEggE+3jmLayhftxh65/kF3W2c47HOlRHOy977IyKHVd0xkHTS7Y5tjb/kWOH8VX/aUNevbG6MQzmjbdeQsEpK+Ah+zc3SeEwM3GpKR13KHwm47fnL6F6o/qyyXs/LNKhxRzunW1+I6+RpN5Cg1F/H+9gmaZuiuq71OgXqr36JdxXy8hlmkuBptvWoFlCvWmET4IkskNy6Yd+XNuuOUiYDmoDVAQVXcZKOkPMm55xKP26FvJaKXygmG09T6qcWbs+9d52Rq/Hevc3Sz0e6eE9md6UubWqgfALDBkrM6pGbfYsjrPZMI03Ijj9k8QObXatAIPiZK4ce73ZHV62UDEwaVJlz0WL62/wwEu++8MR3KDA9OY2VjXjLAdmcNZdwWCKY8nCN8wJFTHzixQ16s5Lx7msh9xK0UsiOXOjxQvYTF+JJ
338262 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - token buffer: 1767 byte(s)
338726 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - continue token: oXYwdKADCgEBoQsGCSqGSIL3EgECAqJgBF5gXAYJKoZIhvcSAQICAwB+TTBLoAMCAQWhAwIBHqQRGA8yMDE2MDMxNjE3MTg1NFqlBQIDAm7epgMCASmpDxsNUEhPRUJVUy5MT0NBTKoPMA2gAwIBAaEGMAQbAmtz
338726 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - continue required: true
339138 [http-bio-9080-exec-2] DEBUG w.servlet.NegotiateSecurityFilter - GET /waffle-filter/, contentlength: -1
339586 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - security package: Negotiate, connection id: 192.168.17.2:52766
339586 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - header: Negotiate oYIGqjCCBqagAwoBAaKCBp0EggaZYIIGlQYJKoZIhvcSAQICAQBuggaEMIIGgKADAgEFoQMCAQ6iBwMFACAAAACjggUWYYIFEjCCBQ6gAwIBBaEPGw1QSE9FQlVTLkxPQ0FMoiYwJKADAgECoR0wGxsESFRUUBsTa3MtcGMuUGhvZWJ1cy5sb2NhbKOCBMwwggTIoAMCARKhAwIBGqKCBLoEggS2ZwETrtauD05HT2ksQ8Fv9KpfZhmvQbqqS0406P9ThCpnUjFvy3tvzZ3UnCxE99dn6wMjz4KC5sMpHtMI0GVVaUKj+OvGyOVvKglh5sEti83GxXJdlaehRN6k56XpYFM8tTTDxJhPXlfpqIKiIKLcfAG6gEetWOtw5p23BUITZ2ShavRsXJDwMbFo94w471R2olrq6L2ny1QWlvWC+R9f2X1HRk/qrNAf+7kihlH8IuBW1lxr4Mc5XD8lcSAzFLsYkM3ybzbFWrtZBNzJwnS9KOJ0pV4lVqmGfwnvSwkEpZCg2Qh1keY0GzJeHqLAiHYKxOU8dBuPd9br3JUkWaGD5jSeSjR6tAzhdVA/m1d08d0wq8JhvhtLYcZX57hCALUfcaehyASxih4mlOH4pIzgcPLQbOels4QWMDZsnwnHALHiDRwJ3FW/9qhtBKv7acBytrBl/ZAYOXz84bc5J5VM8NJDxHjjheIC4zGqvWt9f9eWKizr5LJR/fPYPDtcEbNMcgeyCgClPFo4EsUoL6hSfYv9mPe8YdoVmXq5/NFRH0ajtIuTmFpfUdJHEi1iHJ7KTVsC9ayXtni4HJU3ps5ZGtseCIiyLAmNxp5Jxyb+CdUYq7rnpIxWwGxNorxW6cDgCCjLFP2XJaeLypp65LTL4oSt9bvVy857CyACPFjBrmEhXpJnSQgl4oOQXn26S0+KK7wVtmZ9+9+bo/Eu/KVALXdqyYott2VHu7v7KwMyHtfUIxLbWyQUPGvMW9+/z9iVv/VYn+tovcnGWW0lgaPjGbUL86Tknyq5mlSqxK5Y3gBTihss0PMEmKl09RpJoU+8AoL/O9EF4TzvI6TfBvC8nsP2fupneKbcr0bxViZERHF5XUpsT8k1MfB5FkVbiBrybJeYDXOQ+fKwGJsUDTGwz2/gQp9zATRk+jF7EkW2rFzDSCYmWT4NtdtSBszvLWRsNUzi8kXERdu5UNcWuIDLFKMU9mp/55KI96I700y9eNQA6EqVUWFCl/IBfD4lgSh4ZMpP1BHWD/ZcERm6xgAH+WXlLP5mWwqKBw4umxHfsU9G4MPYb9E6VfboKAOovVKre4aLrV/Jd8Xi44mOUqkTQeVR7fzU8Ol9DAkm/RXOhIqNKx7cmt0kjRsrwNrENYTOGhOaNY2LDag+ANw+4ZpZpnwHTU2jhzTLmElq7Q8dSTnMWupgv4tl26PKiiALHQ2hUhBmG95X3pC7rbt79tnrdTfcjvnQbE+jWyb/1wYZGrt8bz/cJ8Epln5h6SPtPjh4P4PR1axPhsYFDY/3LTDLiTWbDivDPVBm9h42YoacD1qPvoVvchmCA93Rh9H96ObXQHxyYyB0+5DRDTlDnPEBuf9VAbU0BjtNLsvEKXjnGuL+kSueGe5/eJdlr6nu0UujR/Xqd4c3xWhZFqTeA59OuqL8xLa+VqeOPDns3842JpkqAWoZgfAOgbMssF5Gur0DaiOCjaJaLefJtXK+iaUFqRW5eN1XtLwwIu5hyfc8PYUnRV1EKhZR4mtxaked2cpqUayRvLTga4pv7C1rK0hDKTNn3H12lMyVdLtTcGnRFO5qV7kp/+wfh0GdDohTHwhUbruZT36tpIIBTzCCAUugAwIBEqKCAUIEggE+yE2m167Mchj+Wk31pd9ORnTeq1CtI1EXfpVRogEiJJhijw0YBmRI3ydlBDXeMSXjuYCN0GKi52JU/YYJRYItRr2kVxZoDnYVW7V9dnpYZfskuhyfs5v5RFNqCbDUv2bxY4dHZY74OLQao+58LJrooTFDAdYwjm/GULNr0jdOKVvNW9oyPPP53B+yhu5d+olSwsmCmnMlmJgTW+zIpL5mZWJ+DzQ3cL/5xQFn865Nqn/xyNET80FQEFrnKMbjrBKM9oM0C1DSlIz1lv5nuIBCC5bUEYclfjEy9/EU41BNd07UPGpn/MJx7HCo9aVr+kWH5l7QGPOkptTZnMctucSt6JOQJLBZhX8BOl/j3pyJwCQPio891nli/S8obIzRiEUIxLO/7/T6yue9S0ltVMrN2ogpW+T9+Ux0eP15IPIp
339587 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - token buffer: 1710 byte(s)
340012 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - continue token: oWkwZ6ADCgEBomAEXmBcBgkqhkiG9xIBAgIDAH5NMEugAwIBBaEDAgEepBEYDzIwMTYwMzE2MTcxODU2WqUFAgMGyk+mAwIBKakPGw1QSE9FQlVTLkxPQ0FMqg8wDaADAgEBoQYwBBsCa3M=
340013 [http-bio-9080-exec-2] DEBUG w.s.s.NegotiateSecurityFilterProvider - continue required: true`

So you can see I get a continue true on the second pass. It does look a bit strange that I'm getting a short auth header on the working on:

`YHYGBisGAQUFAqBsMGqgMDAuBgorBgEEAYI3AgIKBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHqI2BDROVExNU1NQAAEAAACXsgjiBwAHAC0AAAAFAAUAKAAAAAYBsR0AAAAPS1MtUENQSE9FQlVT`

and a long header on the not working on:

`YIIG4wYGKwYBBQUCoIIG1zCCBtOgMDAuBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCBp0EggaZYIIGlQYJKoZIhvcSAQICAQBuggaEMIIGgKADAgEFoQMCAQ6iBwMFACAAAACjggUWYYIFEjCCBQ6gAwIBBaEPGw1QSE9FQlVTLkxPQ0FMoiYwJKADAgECoR0wGxsESFRUUBsTa3MtcGMuUGhvZWJ1cy5sb2NhbKOCBMwwggTIoAMCARKhAwIBGqKCBLoEggS2uLAxnAn2SHT4xx1kpKpEsML553EKX2BwUXT8WFBjMREWQ7IyQxGVA`

Any idea what is going on here please?

**Comment by dblock** [comment]
Go through regular troubleshooting, https://github.com/dblock/waffle/blob/master/Docs/Troubleshooting.md, and if that doesn't solve it, please ask the mailing list. Usually this is an SPN problem.
