### ISSUE TITLE
Defective token detected when negotiation is Kerberos

### ISSUE THREAD

**Issue by Jasonqian1** [dblock/waffle#336]
This may not right place for this question, but appreciate your help in advance.

Is this Kerberos configuration issue, or we did not implement waffle correctly ?

The client -- httpclient 3.1 and the server -- tomcat with waffle 1.4
windows 2012

Client -->
"Authorization: Negotiate YIIG+gYJKoZIhvcSAQICAQBuggbpMIIG5aADAgEFoQMCAQ6iBwMFACAAAACjggX8YYIF+DCCBfSgAwIBBaE ... about 2k long

Client <---
"WWW-Authenticate: Negotiate YF4GCSqGSIb3EgECAgMAfk8wTaADAgEFoQMCAR6kERgPMjAxNjAzMzEwMTEyMjlapQUCAwPgyaYDAgEpqQ4bDE5BLlRJQkNPLkNPTaoSMBCgAwIBAaEJMAcbBWpxaWFu[\r][\n]"

Client :
[NegotiateScheme] Defective token detected (Mechanism level: AP_REP token id does not match!)

Caused by: GSSException: Defective token detected (Mechanism level: AP_REP token id does not match!)
	at sun.security.jgss.krb5.AcceptSecContextToken.<init>(AcceptSecContextToken.java:83)
	at sun.security.jgss.krb5.Krb5Context.initSecContext(Krb5Context.java:696)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:248)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)

**Comment by dblock** [comment]
This is the same as "authentication failed", albeit a strange error message from jgss. You should go through the regular troubleshooting: https://github.com/dblock/waffle/blob/master/Docs/Troubleshooting.md.

**Comment by dblock** [comment]
Please use the [Google Group](http://groups.google.com/group/waffle-users) for questions.

**Comment by Jasonqian1** [comment]
Thanks Daniel,

I have post the question to Google Group
<http://groups.google.com/group/waffle-users>

I  google this error, someone posted similar issue(not in the waffle
group), but no answer yet.
So, I really appreciate if you have any suggestion on this issue.

Thanks
Jason
