### ISSUE TITLE
Handle leak in WindowsAuthProviderImpl?

### ISSUE THREAD

**Issue by afirmage** [dblock/waffle#355]
I'm using waffle 1.8 with Tomcat 8 for Windows authentication in front of an OpenRDF Sesame 2.7.15 web app and found that every request that comes in leaks an OS Token handle (via using sysinternals handle.exe etc.). This is becoming a big problem on busy systems as the handle count goes in to the 100,000s over a week or so.

It looks like this could possibly come from the handle in the WindowsCredentialsHandleImpl initialized [here](https://github.com/dblock/waffle/blob/master/Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java#L117) into the serverCredential var. This is passed in, and held by, the WindowsSecurityContextImpl sc var, and this is disposed in every case, except when a [successful negotiation](https://github.com/dblock/waffle/blob/master/Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java#L149) completes, in which case it is returned to the caller [here](https://github.com/dblock/waffle/blob/master/Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/NegotiateAuthenticator.java#L112) into the securityContext var.

It looks like the securityContext var needs to be disposed before returning from this method, perhaps in the finally block at the end.

**Comment by dblock** [comment]
This looks legit, please PR?

**Comment by afirmage** [comment]
PR #357
