### ISSUE TITLE
How to use acceptSecurityToken(String, byte[], String) instead of logonUser(String, String)

### ISSUE THREAD

**Issue by gerrit-hohl** [dblock/waffle#363]
Hello everyone,

this question, not a bug.

First I can't express how thankful I'm for this library here. Until now I used some external programs which accepted NTLM and BASIC authentication. In the end I had a lot of processes which I had to handle (Means the in and out of the process). Beside that it took a lot of code to handle it, it also took a lot of resources on the machine (CPU and RAM).
Using this library I can do everything in one Java process. And it takes also almost no resources...

But only "almost". When I use `logonUser(String, String)` for the BASIC authentication the CPU load hits 100%. Of course not from a single authentication, but when you have to do 25 or more at the same time and a lot of them subsequently.
I noticed that doing NTLM using the `acceptSecurityToken(String, byte[], String)` takes almost not CPU.

I guess it is because of what `logonUser(String, String)` does as the load is mainly on the Windows side. Maybe some kind of user context or user space will be created within Windows which takes a lot of resources.

So my idea would be to use `acceptSecurityToken(String, byte[], String)`, but I haven't found any example which uses e.g. Negotiate doing this. I mean I haven't found anything for the client side. The only examples have been using a local context without a password and "authenticated" that using this method. But I'm looking for an example in which I can provide the user and the password for performing this.

Is there any possibility to implement this using the existing waffle classes?

**Comment by dblock** [comment]
The `acceptSecurityToken` workflow is one between multiple computers where the client calls `logonUser`, `initializeSecurityContext`, then sends tokens, then the server does `acceptSecurityContext`. This allows to not exchange usernames and passwords. 

So even if you were able to do this once you have a username and password, you still have to logon the user first.

I think you should find out why `logonUser` is taking so much CPU. This is definitely not normal, in theory the logon delegates the majority of the work to Active Directory and the server just waits on that to complete. Something is probably doing a lot of work, like enumerating too many security groups or such. I would focus your energy there.

I'm going to close this, feel free to ask more questions on the [Waffle Mailing List](http://groups.google.com/group/waffle-users).
