### ISSUE TITLE
Missing spring classes in Spring demo WARs

### ISSUE THREAD

**Issue by alshain** [dblock/waffle#374]
The two spring demos are broken. The [two](https://github.com/dblock/waffle/blob/master/Docs/spring/SpringSecurityAuthenticationProvider.md) [guides](https://github.com/dblock/waffle/blob/master/Docs/spring/SpringSecuritySingleSignOnFilter.md) don't list any additional instructions to get the demos to work.
- `Waffle\Samples\waffle-spring-filter-1.8.0.war`
- `Waffle\Samples\waffle-spring-form-1.8.0.war`

They are missing all Spring related JARs and thus crash when launching the WAR.

**Comment by hazendaz** [comment]
Does 1.8.1 on maven central under demos have same issue?

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Jul 14, 2016 at 5:55 AM -0400, "Chris" <notifications@github.com<mailto:notifications@github.com>> wrote:


The two spring demos are broken. The two<https://github.com/dblock/waffle/blob/master/Docs/spring/SpringSecurityAuthenticationProvider.md> guides<https://github.com/dblock/waffle/blob/master/Docs/spring/SpringSecuritySingleSignOnFilter.md> don't list any additional instructions to get the demos to work.

  *   Waffle\Samples\waffle-spring-filter-1.8.0.war
  *   Waffle\Samples\waffle-spring-form-1.8.0.war

They are missing all Spring related JARs and thus crash when launching the WAR.

-

**Comment by alshain** [comment]
The WARs itself have the same problems, yes.

However, the POM lists a dependency on waffle-spring-security which in turn has dependencies on spring itself.

http://central.maven.org/maven2/com/github/dblock/waffle/demo/waffle-spring-filter/1.8.1/waffle-spring-filter-1.8.1.war
http://central.maven.org/maven2/com/github/dblock/waffle/demo/waffle-spring-form/1.8.1/waffle-spring-form-1.8.1.war

**Comment by hazendaz** [comment]
Fixing issue.  The spring depencencies were listed as 'provided' scope.  I cannot think of a reason why we have them listed that way.  So changing them to compile scope.  Will close this issue as soon as code hits master in a few...
