### ISSUE TITLE
Error in DelegatingNegotiateSecurityFilter when not setting custom authenticationManager

### ISSUE THREAD

**Issue by unaor** [dblock/waffle#381]
The override for setAuthentication is missing an else clause if the authenticationManager is null
else {
                SecurityContextHolder.getContext().setAuthentication(authentication);
            }

Im using this in a spring boot application and i need just custom error handlers so im not setting a particular authenticationManager (yet)

**Comment by dblock** [comment]
Please make a pull request.

**Comment by unaor** [comment]
pull request created and looks like its confirmed let me know when you can merge trunk

**Comment by hazendaz** [comment]
Was this fixed?  I'm thinking it was but wanted to confirm before closing the ticket.

**Comment by hazendaz** [comment]
This was fixed on PR #382
