### ISSUE TITLE
Tomcat 8.5.5 AbstractMethodError

### ISSUE THREAD

**Issue by p33t** [dblock/waffle#389]
It appears the latest revision of Tomcat 8.5 has broken Waffle.

When deploying to 8.5.4 everything works fine but deploying to 8.5.5 and navigating to a secure resource results in:

**message org.apache.catalina.authenticator.AuthenticatorBase.doAuthenticate(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;)Z**

**exception
java.lang.AbstractMethodError: org.apache.catalina.authenticator.AuthenticatorBase.doAuthenticate(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;)Z
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:551)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
...**

I'm using the [Mixed Authenticator](https://github.com/dblock/waffle/blob/master/Docs/tomcat/TomcatMixedSingleSignOnAndFormAuthenticatorValve.md) and noticed the doco says jna-4.2.2 but [the pom](http://central.maven.org/maven2/com/github/dblock/waffle/waffle-jna/1.8.1/waffle-jna-1.8.1.pom) says 4.2.1.  Manually putting in 4.2.2 jars does NOT fix the problem.

Release notes for 8.5.5 mention changes to the 'Rewrite Valve' (?).
See http://tomcat.apache.org/ and
http://tomcat.apache.org/tomcat-8.5-doc/changelog.html#Tomcat_8.5.5_(markt)

**Comment by hazendaz** [comment]
8.5.5 and 9.0.0.m10 have breaking changes.  Quick patch would be to implement that method and do nothing with it.  I have done that much on my fork but not sure how we might want to proceed and if we can retain any backwards support.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Sep 13, 2016 at 2:35 AM -0400, "Peter Leong" <notifications@github.com<mailto:notifications@github.com>> wrote:


It appears the latest revision of Tomcat 8.5 has broken Waffle.

When deploying to 8.5.4 everything works fine but deploying to 8.5.5 and navigating to a secure resource results in:

message org.apache.catalina.authenticator.AuthenticatorBase.doAuthenticate(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;)Z

exception
java.lang.AbstractMethodError: org.apache.catalina.authenticator.AuthenticatorBase.doAuthenticate(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;)Z
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:551)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
...

I'm using the Mixed Authenticator<https://github.com/dblock/waffle/blob/master/Docs/tomcat/TomcatMixedSingleSignOnAndFormAuthenticatorValve.md> and noticed the doco says jna-4.2.2 but the pom<http://central.maven.org/maven2/com/github/dblock/waffle/waffle-jna/1.8.1/waffle-jna-1.8.1.pom> says 4.2.1. Manually putting in 4.2.2 jars does NOT fix the problem.

Release notes for 8.5.5 mention changes to the 'Rewrite Valve' (?).
See http://tomcat.apache.org/ and
http://tomcat.apache.org/tomcat-8.5-doc/changelog.html#Tomcat_8.5.5_(markt)

-

**Comment by tommytan27** [comment]
Hi there, I am integrating tomcat 9.0.0.M13 with the waffle (1.8.0) and got the same exact exception.
I thought it has been fixed on 9.0.0.M11 (according to the pull request merged to solve this issue). Can someone please guide me on what else I need to do to get it working? Thanks

**Comment by hazendaz** [comment]
Are you using the snapshot?  It's only supported on waffle 1.8.2-SNAPSHOT currently.  You can find them [here](https://oss.sonatype.org/content/repositories/snapshots/com/github/waffle/)

**Comment by cthiebaud** [comment]
sorry for the late response, thanks for the upload, works perfectly..
